/// A set of bindings that can be used to generate native packages.
resource bindings {
    generate-python: func() -> expected<list<file>, error>
    generate-javascript: func() -> expected<list<file>, error>
}

/// An error that may occur.
record error {
    /// The error message.
    message: string,
    /// An extended error message, possibly including a backtrace and the list
    /// of errors which led to this one.
    verbose: string,
    /// The chain of source errors.
    causes: list<string>,
}

record file {
    filename: string,
    contents: list<u8>,
}

load-bindings: func(name: string, contents: string, wasm: list<u8>) -> expected<bindings, error>
