/// A set of bindings that can be used to generate native packages.
resource bindings {
    generate-python: func(output-dir: string) -> expected<unit, error>
    generate-javascript: func(output-dir: string) -> expected<unit, error>
}

/// An error that may occur.
record error {
    /// The error message.
    message: string,
    /// An extended error message, possibly including a backtrace and the list
    /// of errors which led to this one.
    verbose: string,
    /// The chain of source errors.
    causes: list<string>,
}

parse: func(name: string, contents: string, wasm: list<u8>) -> expected<bindings, error>

parse-from-disk: func(wit-file-path: string, wasm-path: string) -> expected<bindings, error>
